// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe2gIyVd4chDpYAiTHpG3dWtcmYyj486Y',
    appId: '1:82499568867:web:f418dff8b083531b8e71d6',
    messagingSenderId: '82499568867',
    projectId: 'belquistours-893d9',
    authDomain: 'belquistours-893d9.firebaseapp.com',
    storageBucket: 'belquistours-893d9.appspot.com',
    measurementId: 'G-LN36VQ8JLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrDBo5DexadBcfxjIRCK8xbE0JDBtwKNE',
    appId: '1:82499568867:android:af744b4cc75f75f68e71d6',
    messagingSenderId: '82499568867',
    projectId: 'belquistours-893d9',
    storageBucket: 'belquistours-893d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-CFZ2glpsgRBIF1Tho7b9RO7pkL1rOw',
    appId: '1:82499568867:ios:8c806dc7862f07e78e71d6',
    messagingSenderId: '82499568867',
    projectId: 'belquistours-893d9',
    storageBucket: 'belquistours-893d9.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-CFZ2glpsgRBIF1Tho7b9RO7pkL1rOw',
    appId: '1:82499568867:ios:c2b69cee654b582f8e71d6',
    messagingSenderId: '82499568867',
    projectId: 'belquistours-893d9',
    storageBucket: 'belquistours-893d9.appspot.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
