// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQAEwHbquwYMZGnWzP13C2FVFZszwqsRI',
    appId: '1:11015802386:web:06c22e7767d127ff0bd2cb',
    messagingSenderId: '11015802386',
    projectId: 'belquis-app',
    authDomain: 'belquis-app.firebaseapp.com',
    storageBucket: 'belquis-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6DAUeDzFMnPcjtJlt-EF1A4NDbkmhfk',
    appId: '1:11015802386:android:e17bd3bf4cf6ff560bd2cb',
    messagingSenderId: '11015802386',
    projectId: 'belquis-app',
    storageBucket: 'belquis-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfIteGOyMWtcRpQGu2gh6_d6Sk8eD2SOE',
    appId: '1:11015802386:ios:94a93ca04e1716b10bd2cb',
    messagingSenderId: '11015802386',
    projectId: 'belquis-app',
    storageBucket: 'belquis-app.appspot.com',
    androidClientId: '11015802386-vripe36prctpi0ktrmq558sieh5m2u8l.apps.googleusercontent.com',
    iosClientId: '11015802386-02s0tn9cn7gll74acua2g64u1k8mccdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfIteGOyMWtcRpQGu2gh6_d6Sk8eD2SOE',
    appId: '1:11015802386:ios:235c47ca1834f4e40bd2cb',
    messagingSenderId: '11015802386',
    projectId: 'belquis-app',
    storageBucket: 'belquis-app.appspot.com',
    androidClientId: '11015802386-vripe36prctpi0ktrmq558sieh5m2u8l.apps.googleusercontent.com',
    iosClientId: '11015802386-bee42cm8hgtq8nskjsh1ddo4ul1svb5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
